version: '3.8'

services:
  redis-node-1:
    image: redis:7.0.0
    ports:
      - 7000:6379
    volumes:
      - ../redis-cluster/node-1/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-2:
    image: redis:7.0.0
    ports:
      - 7001:6379
    volumes:
      - ../redis-cluster/node-2/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-3:
    image: redis:7.0.0
    ports:
      - 7002:6379
    volumes:
      - ../redis-cluster/node-3/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-4:
    image: redis:7.0.0
    ports:
      - 7003:6379
    volumes:
      - ../redis-cluster/node-4/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-5:
    image: redis:7.0.0
    ports:
      - 7004:6379
    volumes:
      - ../redis-cluster/node-5/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-6:
    image: redis:7.0.0
    ports:
      - 7005:6379
    volumes:
      - ../redis-cluster/node-6/data:/data
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes

  redis-setup:
    image: redis:7.0.0
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: >
      sh -c "
      sleep 10;
      echo yes | redis-cli --cluster create 
      redis-node-1:6379 
      redis-node-2:6379 
      redis-node-3:6379 
      redis-node-4:6379 
      redis-node-5:6379 
      redis-node-6:6379 
      --cluster-replicas 1"
